### ISSUE TITLE
a.button

### ISSUE THREAD

**Issue by josiemedel** [Blake-C/mobile-mega-menu#5]
There is a style that is too broad that changes all buttons on the site once the mobile mega menu styles are added to your site. All buttons show up the default purple that is specified in the styles. It would be nice if the `a.button` was removed or made more specific to the mega menu. Let me know if you have any questions and I can show you what I mean. 

Check line 44 of the sass file.

`a.button {
    background: #4651a0;
    color: #fff;
    float: left;
    font-family: Helvetica Neue,Helvetica,Arial,sans-serif;
    font-size: 1.1em;
    font-weight: 200;
    padding: 15px 2.5% 20px;
    text-align: center;
    text-decoration: none;
    width: 50%;
}`

![image](https://cloud.githubusercontent.com/assets/9933983/26703158/e052ec2c-46ed-11e7-8a17-c23588386030.png)

Buttons above should be a light blue, not purple, nor should they have the font that is being used, etc.

**Comment by Blake-C** [comment]
I've adjusted the styles in the mobile-mega-menu stylesheet to not rely on the generic button class name and instead have it nested with a modifier class so the plugins styles will only work with an mmm class on the button element. Otherwise you can rely on the sites button styles to apply to your toggle buttons.

I've published the changes and pushed the update to npm at v1.0.4

https://github.com/Blake-C/mobile-mega-menu/commit/c1302669fc4aadd6a51127e3f221e8f4a003be8b

This should solve your issues. Another solution to this would be to duplicate the plugins stylesheet into a vendor directory in your project and not include the one provided in the build, then just change what you want specific to your project.
